### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by Jamminroot** [ScottPlot/ScottPlot#1649]
## Bug Report

![image](https://user-images.githubusercontent.com/6387654/152952793-b03828d0-1de5-4c47-a984-f4b21667c672.png)

**Issue:** Rendering text on linux vps only gives squares

**Reproducing:** assemble a plot, add a legend. String for a plot is regular text in us: (copy&paste): `DeltaError` 

```cs
var plt = new Plot(640, 480);
foreach (var metric in metrics)
{
    if (metric.Equals("UndefinedData")) continue;
    double[] xs;
    double[] ys;
    double[] errs;
    
    xs = settings.Metrics[metric].Keys.Skip(settings.Metrics[metric].Count -  PlotDepth).Select(k => (double) k).ToArray();
    ys = settings.Metrics[metric].Values.Skip(settings.Metrics[metric].Count -  PlotDepth).Select(v => (double) v).ToArray();
    errs = settings.Metrics["UndefinedData"].Values.Skip(settings.Metrics[metric].Count - PlotDepth).Select(v => (double) v)
	    .ToArray();
    
    plt.AddScatter(xs, ys, label: metric,markerSize: 3f);
    plt.AddErrorBars(xs, ys, null, errs);
}
plt.Legend(true, Alignment.LowerLeft);
plt.Title(name);
using (var ms = new MemoryStream())
using (var finalImage = plt.Render())
{
    finalImage.Save(ms, ImageFormat.Png);
    ms.Position = 0;
    await botClient.SendPhotoAsync(message.Chat.Id, ms);
}
```

### System Details
* **ScottPlot Version:** 4.1.33?
* **Operating System:** VERSION="20.04.3 LTS (Focal Fossa)"
* **Application Type:** console
* **.NET Version:** .NET 5.0

**Comment by Jamminroot** [comment]
Now that I think about it, can it be because some fonts are missing on the OS? If so - what font is required?

**Comment by swharden** [comment]
Hi @Jamminroot 

I recall seeing this before on Linux.

Try installing the ´System.Drawing.Common´ NuGet package in your project and see if that fixes it 👍

* #340
*#1079

**Comment by Jamminroot** [comment]
Thanks a lot, and sorry for missing those (I actually did search for "Encoding", and not "font", probs this is why missed :D)

That did help me (not version 6.0.0 though as it's now incompatible, iirc), 5.0.3 works just fine.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
   at System.Drawing.LibraryResolver.EnsureRegistered()
   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipNewInstalledFontCollection(IntPtr& fontCollection)
   at ScottPlot.Drawing.InstalledFont.ValidFontName(String[] fontNames)
   at ScottPlot.Drawing.InstalledFont.Monospace()
   at ScottPlot.Renderable.Message..ctor()
   at ScottPlot.Renderable.BenchmarkMessage..ctor()
   at ScottPlot.Settings..ctor()
   at ScottPlot.Plot..ctor(Int32 width, Int32 height)
```

Thanks a lot for your amazing work!
