### ISSUE TITLE
ThreadException - Plottable added in Form's constructor

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2126]
Hi!

**Issue:** 
I have a framework, which creates a Form object, then dynamically loads it into a TAB page. Unfortunatelly I cannot share this framework, but it does this dynamic Form loading in a separate thread.
I have an init method which I call from the constructor of the Form class. It throws an error if I keep these two lines in it:
```
formsPlot1.Plot.Add(plotTemp);
formsPlot1.Plot.Add(plotHumid);  
```
If I add the two SignalPlotXY objects to the Plot outside of the constructor, no error.
I am curious what is wrong in the case of the constructor call?
Thanks! 

```cs
private void InitChart()
        {
            plotTemp = new SignalPlotXY();
            plotHumid = new SignalPlotXY();

            formsPlot1.Configuration.Quality = ScottPlot.Control.QualityMode.High;
            formsPlot1.Plot.XAxis.TickLabelFormat("MM.dd HH:mm:ss", dateTimeFormat: true);
            formsPlot1.Plot.XAxis.Label("Time", size: 15);
            formsPlot1.Plot.YAxis.Label("Temperature (°C)", size: 15);
            formsPlot1.Plot.YAxis2.Label("Humidity (%)", size: 15);
            formsPlot1.Plot.YAxis2.Ticks(true);

            // unsubscribe from the default right-click menu event
            formsPlot1.RightClicked -= formsPlot1.DefaultRightClickEvent;

            legend = formsPlot1.Plot.Legend(location: Alignment.UpperRight);
            legend.IsVisible = true;
            legend.FontSize = 15;
            plotTemp.LineColor = Color.Red;
            plotTemp.MarkerColor = Color.Red;
            plotTemp.MarkerSize = 5;
            plotTemp.LineWidth = 2;
            plotTemp.Label = "Temperature (°C)";
            plotHumid.LineColor = Color.Blue;
            plotHumid.MarkerColor = Color.Blue;
            plotHumid.MarkerSize = 5;
            plotHumid.LineWidth = 2;
            plotHumid.Label = "Humidity (%)";
            plotHumid.YAxisIndex = 1;
            plotTemp.IsVisible = cbTemp.Checked;
            plotHumid.IsVisible = cbTemp.Checked;
            formsPlot1.Plot.YAxis.Grid(cbTemp.Checked);
            formsPlot1.Plot.YAxis2.Grid(cbHumid.Checked);

            formsPlot1.Plot.Add(plotTemp);
            formsPlot1.Plot.Add(plotHumid);                     
        }
```

Error info:

```
ERROR: ThreadException in ScottPlot: Object reference not set to an instance of an object.
   at ScottPlot.MinMaxSearchStrategies.LinearDoubleOnlyMinMaxStrategy.MinMaxRangeQuery(Int32 l, Int32 r, Double& lowestValue, Double& highestValue)
   at ScottPlot.Plottable.SignalPlotBase`1.GetAxisLimits()
   at ScottPlot.Plottable.SignalPlotXYGeneric`2.GetAxisLimits()
   at ScottPlot.Settings.<>c.<AxisAutoX>b__64_2(IPlottable x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ScottPlot.Settings.AxisAutoX(Int32 xAxisIndex, Nullable`1 margin)
   at ScottPlot.Settings.AxisAutoUnsetAxes(Nullable`1 horizontalMargin, Nullable`1 verticalMargin)
   at ScottPlot.Plot.Render(Bitmap bmp, Boolean lowQuality, Double scale)
   at ScottPlot.Control.ControlBackEnd.Render(Boolean lowQuality, Boolean skipIfCurrentlyRendering)
   at ScottPlot.Control.ControlBackEnd.ProcessEvent(IUIEvent uiEvent)
   at ScottPlot.Control.ControlBackEnd.RenderRequest(RenderType renderType)
   at ScottPlot.Control.ControlBackEnd.Resize(Single width, Single height, Boolean useDelayedRendering)
   at ScottPlot.FormsPlot.OnSizeChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   at System.Windows.Forms.Layout.DefaultLayout.xLayoutDockedControl(IArrangedElement element, Rectangle newElementBounds, Boolean measureOnly, Size& preferredSize, Rectangle& remainingBounds)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(IArrangedElement container, Boolean measureOnly)
   at System.Windows.Forms.Layout.DefaultLayout.xLayout(IArrangedElement container, Boolean measureOnly, Size& preferredSize)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   at System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.ScrollableControl.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.PerformLayout()
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at System.Windows.Forms.Control.ResumeLayout()
   at System.Windows.Forms.SplitContainer.ResizeSplitContainer()
   at System.Windows.Forms.SplitContainer.OnLayout(LayoutEventArgs e)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.PerformLayout(IArrangedElement affectedElement, String affectedProperty)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.SplitContainer.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   at System.Windows.Forms.Layout.DefaultLayout.xLayoutDockedControl(IArrangedElement element, Rectangle newElementBounds, Boolean measureOnly, Size& preferredSize, Rectangle& remainingBounds)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(IArrangedElement container, Boolean measureOnly)
   at System.Windows.Forms.Layout.DefaultLayout.xLayout(IArrangedElement container, Boolean measureOnly, Size& preferredSize)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   at System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.ScrollableControl.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.PerformLayout(IArrangedElement affectedElement, String affectedProperty)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.Panel.OnResize(EventArgs eventargs)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.TabPage.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.SetBounds(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.set_Bounds(Rectangle value)
   at System.Windows.Forms.TabControl.ResizePages()
   at System.Windows.Forms.TabControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### System Details
* **ScottPlot Version:** 4.1.58
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** NET Framework 4.8

**Comment by swharden** [comment]
Hi @bukkideme,

I think the problem is because the signal plots' `Xs` and `Ys` are not getting set in the constructor

I'm guessing you have a timer or something that is assigning those values elsewhere in your code (not shown) which is why it worked elsewhere

Let me know if that doesn't do the trick!

**Comment by bukkideme** [comment]
yep, that was the problem, thanks! :)
