### ISSUE TITLE
Exception occurs trying to launch ScottPlot Cookbook 4.1.60 from compiled source

### ISSUE THREAD

**Issue by mkane7** [ScottPlot/ScottPlot#2332]
**ScottPlot Version:** 4.1.60
**Operating System:** Windows 10
**Application Type:**  WinForms 
**Question:** Why did this happen and how do I fix it?

I downloaded the source code for ScottPlot 4.1.60 from https://github.com/ScottPlot/ScottPlot and extracted all the files.
I compiled ScottPlot4.sln in Visual Studio Community 2022 and set WinForms Demo (target framework 4.8) as the Startup Application. 
In the debugger, I launched the WinForm Demo.  I can click the buttons "Plot Viewer', 'Mouse Tracker', etc on the right-hand side and the demos run successfully.
![image](https://user-images.githubusercontent.com/47332626/209762343-606eec0a-7cfa-4f71-95d8-d52463b128d5.png)

However, when I click on the 'Launch ScottPlot Cookbook' button the following exception occurs.
![image](https://user-images.githubusercontent.com/47332626/209762472-48b06e42-0ea8-44a8-9691-4b060d07a6c0.png)

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'ScottPlot.Cookbook.Locate' threw an exception.
  Source=ScottPlot.Cookbook
  StackTrace:
   at ScottPlot.Cookbook.Locate.GetCategorizedRecipes() in C:\Users\mkane\Downloads\ScottPlot-main\src\ScottPlot4\ScottPlot.Cookbook\Locate.cs:line 68
   at ScottPlot.Demo.WinForms.FormCookbook.LoadTreeWithDemosNew() in C:\Users\mkane\Downloads\ScottPlot-main\src\ScottPlot4\ScottPlot.Demo\ScottPlot.Demo.WinForms\FormCookbook.cs:line 26
   at ScottPlot.Demo.WinForms.FormCookbook..ctor() in C:\Users\mkane\Downloads\ScottPlot-main\src\ScottPlot4\ScottPlot.Demo\ScottPlot.Demo.WinForms\FormCookbook.cs:line 16
   at ScottPlot.Demo.WinForms.FormMain.CookbookButton_Click(Object sender, EventArgs e) in C:\Users\mkane\Downloads\ScottPlot-main\src\ScottPlot4\ScottPlot.Demo\ScottPlot.Demo.WinForms\FormMain.cs:line 17
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at ScottPlot.Demo.WinForms.Program.Main() in C:\Users\mkane\Downloads\ScottPlot-main\src\ScottPlot4\ScottPlot.Demo\ScottPlot.Demo.WinForms\Program.cs:line 20

  This exception was originally thrown at this call stack:

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
FileLoadException: Could not load file or assembly 'System.Drawing.Common, Version=4.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

If it helps here are the dependencies for ScottPlot.Cookbook 
![image](https://user-images.githubusercontent.com/47332626/209762663-d48b009d-4396-4a07-b0be-c36e5add5bc9.png)

I assume the executable is running from
C:\Users\mkane\Downloads\ScottPlot-main\src\ScottPlot4\ScottPlot.Demo\ScottPlot.Demo.WinForms\bin\Debug\net48\ScottPlot.Demo.WinForms.exe

In that directory there is 
2018-09-18  02:38 PM            51,248 System.Drawing.Common.dll

With the following details
![image](https://user-images.githubusercontent.com/47332626/209763294-592fa456-6c7d-49f0-b203-7088f0de3049.png)

The exception says:  Could not load file or assembly 'System.Drawing.Common, Version=4.0.0.2,"    Is the problem that the dll in the directory is not the right version?  What is the solution?

**Comment by swharden** [comment]
Hi @mkane7, this surprises me! I just searched the code base and it looks like all csproj files want 4.7.2 or 5.0.2 🤔 

Here are my suggestions:
* make sure you're sync'd with the latest git source code
* close visual studio
* delete the `bin` and `obj` folders inside each project folder
  * /src/ScottPlot4/ScottPlot/ScottPlot
  * /src/ScottPlot4/ScottPlot/ScottPlot.Cookbook ⚠️ this one is most likely causing your issue
  * /src/ScottPlot4/ScottPlot/ScottPlot.WinForms
  * /src/ScottPlot4/ScottPlot/ScottPlot.Demo/ScottPlot.Demo/WinForms
  * /src/ScottPlot4/ScottPlot/ScottPlot.Tests
* start Visual Studio again
* run all the tests (to force a rebuild and regenerate the cookbook)
* set the demo project to launch on startup
* press F5 and cross your fingers 🤞 

I'm pretty confident this will work and will close this issue, but if it doesn't do the trick we can re-open this and figure it out together! 🚀 

![image](https://user-images.githubusercontent.com/4165489/209814916-1079a09d-cc03-4ae2-aba1-82520c330878.png)
