### ISSUE TITLE
SP5 Tests: Why does `dotnet test` crash but running tests in VS works? 🔥

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3123]
Open the full solution and run tests, no problem

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/91a01088-4fc7-483b-b225-b425ff452df8)

However if I open a console in `src\ScottPlot5\ScottPlot5 Tests` and `dotnet test` I get:

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SkiaSharp.SKAbstractManagedWStream.WriteInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)
   at SkiaSharp.SkiaApi.sk_canvas_destroy(IntPtr param0)
   at SkiaSharp.SKCanvas.DisposeNative()
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKObject.Dispose(Boolean disposing)
   at SkiaSharp.SKCanvas.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.Finalize()
```

It seems to be sensitive to the number of tests. Using various `--filter` options I found that this error happens when there are about 35 images, but no test itself causes the crash

**Comment by swharden** [comment]
More info, the ScottPlot cookbook test project _seems_ heavier, but it runs fine (61 tests)

**Comment by swharden** [comment]
Adding `[SetUpFixture]` to each class solves this issue, but I'm still unsure why

**Comment by swharden** [comment]
minimal reproducible error:

Keep just these files

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/c85d463e-3d5d-4114-bd83-2cda6507989e)

```
dotnet test --filter=RenderTests
```

**Comment by swharden** [comment]
new information: combining all `[Test]` methods into a single class prevents this issue

**Comment by swharden** [comment]
new information: added `[Parallelizable(ParallelScope.Children)]` to classes prevents this issue

https://docs.nunit.org/articles/nunit/writing-tests/attributes/parallelizable.html

**Comment by swharden** [comment]
More details! I can recreate the issue if I run the VS tests in debug mode

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/74a70a6d-5e1b-48aa-8067-3b1300c3171e)

**Comment by swharden** [comment]
I think this bit of code may be the culprit

https://github.com/ScottPlot/ScottPlot/blob/6b3ee06f5f946c4a35312cf9922974bd424d2e28/src/ScottPlot5/ScottPlot5/Legends/Legend.cs#L63-L70

**Comment by swharden** [comment]
I think this bit of code may be the culprit

https://github.com/ScottPlot/ScottPlot/blob/6b3ee06f5f946c4a35312cf9922974bd424d2e28/src/ScottPlot5/ScottPlot5/Legends/Legend.cs#L72-L79

**Comment by swharden** [comment]
After several hours I figured out the two tests that call `GetLegendImage()` and `GetLegendSvg()` can be disabled and tests run fine. I suspect this bug was introduced in #3062. I'll close this issue and re-open #2934
