### ISSUE TITLE
Avalonia: Call from invalid thread

### ISSUE THREAD

**Issue by BendRocks** [ScottPlot/ScottPlot#3359]
**Issue:** 
Shared axis doesn't work under Avalonia. Hangs with invalid thread exception upon launch. If you set a break point in the ApplyLayoutToOtherPlot(), you'll see that is called from a worker thread named DwmRenderTimerLoop. If the Refresh is called using InvokeAsync inside that method, it works.

Curiously, if the ApplyLayoutToOtherPlot is tagged as async and Refresh is called directly, breakpoint happens.  Without async and a with a direct call to Refresh, the app silently hangs.

Not sure if this is by design or a bug. 

**ScottPlot Version:**
ScottPlot Avalonia 5.0.21
Avalonia 11.0.2 (MVVM, Community toolkit)

## MainWindow.axaml:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:ScottPlot5Test.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="ScottPlot5Test.Views.MainWindow"
		xmlns:scottplot="clr-namespace:ScottPlot.Avalonia;assembly=ScottPlot.Avalonia"
        x:DataType="vm:MainWindowViewModel"
        Icon="/Assets/avalonia-logo.ico"
        Title="ScottPlot5Test">

	<Design.DataContext>
		<!-- This only sets the DataContext for the previewer in an IDE,
             to set the actual DataContext for runtime, set the DataContext property in code (look at App.axaml.cs) -->
		<vm:MainWindowViewModel/>
	</Design.DataContext>

	<StackPanel>
		<TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center"/>
		<Grid RowDefinitions="150,150">
			<scottplot:AvaPlot Grid.Row="0" Name="Plot0"></scottplot:AvaPlot>
			<scottplot:AvaPlot Grid.Row="1" Name="Plot1"></scottplot:AvaPlot>
		</Grid>
	</StackPanel>
</Window>
```

## MainWindow.axaml.cs
```
using Avalonia.Controls;
using ScottPlot;

namespace ScottPlot5Test.Views
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            //Plot0.Plot.Axes.SetLimits(0, 10, -1, 1);
            //Plot0.Plot.Axes.SetLimits(0, 10, -1, 1);

            Plot0.Plot.RenderManager.AxisLimitsChanged += (s, e) =>
            {
                ApplyLayoutToOtherPlot(Plot0, Plot1);
            };

            //Plot0.Refresh();
            //Plot1.Refresh();
        }

        private async void ApplyLayoutToOtherPlot(IPlotControl source, IPlotControl dest)
        {
            AxisLimits axesBefore = dest.Plot.Axes.GetLimits();
            dest.Plot.Axes.SetLimitsX(source.Plot.Axes.GetLimits());
            AxisLimits axesAfter = dest.Plot.Axes.GetLimits();
            if (axesBefore != axesAfter)
            {
                // This line causes a thread exception
                dest.Refresh();

                // This line works
                //await Dispatcher.UIThread.InvokeAsync(dest.Refresh);
            }
        }
    }
}
```

Exception occurs on run without any user interaction:

```
Exception thrown: 'System.InvalidOperationException' in Avalonia.Base.dll
[Visual]Exception when rendering: 'System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|16_0()
   at Avalonia.Threading.Dispatcher.VerifyAccess()
   at Avalonia.Rendering.Composition.Compositor.RequestCompositionUpdate(Action action)
   at Avalonia.Rendering.Composition.CompositingRenderer.QueueUpdate()
   at Avalonia.Rendering.Composition.CompositingRenderer.AddDirty(Visual visual)
   at Avalonia.Visual.InvalidateVisual()
   at ScottPlot.Avalonia.AvaPlot.Refresh()
   at ScottPlot5Test.Views.MainWindow.ApplyLayoutToOtherPlot(IPlotControl source, IPlotControl dest) in C:\Users\USER\Documents\VisualStudio\Junk\ScottPlot5Test\Views\MainWindow.axaml.cs:line 31
   at ScottPlot5Test.Views.MainWindow.<.ctor>b__0_0(Object s, RenderDetails e) in C:\Users\USER\Documents\VisualStudio\Junk\ScottPlot5Test\Views\MainWindow.axaml.cs:line 17
   at ScottPlot.Rendering.RenderManager.Render(SKCanvas canvas, PixelRect rect)
   at ScottPlot.Plot.Render(SKCanvas canvas, PixelRect rect)
   at ScottPlot.Avalonia.AvaPlot.CustomDrawOp.Render(ImmediateDrawingContext context)
   at Avalonia.Rendering.Composition.Drawing.Nodes.RenderDataCustomNode.Invoke(RenderDataNodeRenderContext& context)
   at Avalonia.Rendering.Composition.Drawing.ServerCompositionRenderData.Render(IDrawingContextImpl context)
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #39179857)
```

**Comment by ykarpeev** [comment]
I think it's normal for avalonia that you'd have to do "await Dispatcher.UIThread.InvokeAsync(dest.Refresh);" to run it from the UI thread.
