### ISSUE TITLE
Avalonia: NullPointerException in DRM on Raspberry Pi 5

### ISSUE THREAD

**Issue by pkstrsk** [ScottPlot/ScottPlot#3532]
**Issue:** (Describe the bug here)

**ScottPlot Version:** 5.0.21 (5.0.22 is having some rendering issues, already tracked as issue here on github)

The setup I am working with is a little complex to debug, as everything is working fine on Windows during Debug and Release. 
I have a Raspberry 5 with latest raspbian 64bit and I run the Avalonia app in DRM mode.
Once on the raspi, I attach remote debugger to get some info out of the app.

I get a situtation, when dragging the cursor (created in GetNearestValues()) across. It works for a decent amount of time and sometimes, just out of the blue it freezes the entire UI. Happens also on a different section of the app that uses data streamer, but that is a different exception. 

I tried to put the entire app in a try-catch block, but it never triggers. Seems like rest of the threads on the app keep running..

**Code Sample:** I'm pretty sure this is where the exception is thrown.

```cs
RawPlot.PointerMoved += (s, e) =>
{
                        Coordinates mouseCoordinatesRaw = RawPlot.Plot.GetCoordinates(new((int)e.GetPosition(RawPlot).X, (int)e.GetPosition(RawPlot).Y));
                        GetNearestValues(mouseCoordinatesRaw, PlotType.Raw);
};
```
And the exception I am getting:
```
[Visual]Exception when rendering: 'System.NullReferenceException: Object reference not set to an instance of an object.
   at ScottPlot.Axes.GetPixel(Coordinates coordinates)
   at ScottPlot.Plottables.Crosshair.Render(RenderPack rp)
   at ScottPlot.Rendering.RenderActions.RenderPlottables.Render(RenderPack rp)
   at ScottPlot.Rendering.RenderManager.Render(SKCanvas canvas, PixelRect rect)
   at ScottPlot.Avalonia.AvaPlot.CustomDrawOp.Render(ImmediateDrawingContext context)
   at Avalonia.Rendering.Composition.Drawing.ServerCompositionRenderData.Render(IDrawingContextImpl context)
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #26692260)
```

And if someone wonders, the one I get in data streamer (same trouble, works for a while, then freezes):
```
[Visual]Exception when rendering: 'System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ScottPlot.DataViews.Scroll.Render(RenderPack rp)
   at ScottPlot.Plottables.DataStreamer.Render(RenderPack rp)
   at ScottPlot.Rendering.RenderActions.RenderPlottables.Render(RenderPack rp)
   at ScottPlot.Rendering.RenderManager.Render(SKCanvas canvas, PixelRect rect)
   at ScottPlot.Avalonia.AvaPlot.CustomDrawOp.Render(ImmediateDrawingContext context)
   at Avalonia.Rendering.Composition.Drawing.ServerCompositionRenderData.Render(IDrawingContextImpl context)
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #60207071)
```

**Comment by swharden** [comment]
> The setup I am working with is a little complex to debug

This is the major reason there hasn't been movement on this issue in a while 😅 

However, there are some new strategies to improve safety in multi-threaded applications! https://scottplot.net/faq/async/
