### ISSUE TITLE
Controls: `InvalidCastException` when starting mouse interaction in the Title area

### ISSUE THREAD

**Issue by pkstrsk** [ScottPlot/ScottPlot#3543]
**Issue:** System.InvalidCastException: 'Unable to cast object of type 'ScottPlot.Panels.TitlePanel' to type 'ScottPlot.IAxis'.'

**ScottPlot Version:** 5.0.23 (Avalonia)

**Code Sample:** Default plot settings, empty app with any plot

Plot.Interactions set to default. Setting them to only zoom or pan also introduces the issue.

I have tested on 5.0.21 and the issue is not there.

**Comment by pkstrsk** [comment]
Just tested on the Demo 5.0.22 and I can get it to crash as well, just by click and drag from the plot title.
![image](https://github.com/ScottPlot/ScottPlot/assets/14115952/05d345ab-e944-49da-a611-49724fc4e5e1)

Full exception
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'ScottPlot.Panels.TitlePanel' to type 'ScottPlot.IAxis'.
   at ScottPlot.Plot.GetAxis(Pixel pixel) in /_/src/ScottPlot5/ScottPlot5/Plot.cs:line 171
   at ScottPlot.Control.StandardActions.DragPan(IPlotControl control, MouseDrag drag, LockedAxes locked) in /_/src/ScottPlot5/ScottPlot5/Control/StandardActions.cs:line 84
   at ScottPlot.Control.Interaction.MouseDrag(Pixel from, Pixel to, MouseButton button, IEnumerable`1 keys, MultiAxisLimitManager start) in /_/src/ScottPlot5/ScottPlot5/Control/Interaction.cs:line 106
   at ScottPlot.Control.Interaction.OnMouseMove(Pixel newPosition) in /_/src/ScottPlot5/ScottPlot5/Control/Interaction.cs:line 78
   at ScottPlot.WinForms.FormsPlotBase.SKElement_MouseMove(Object sender, MouseEventArgs e) in /_/src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotBase.cs:line 83
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Private.CoreLib.dll
----------------------------------------
WinForms Demo
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/<USER>/AppData/Local/Temp/Rar$EXa80260.18640/scottplot-5.0-demo-winforms/WinForms%20Demo.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2824.12004
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.28/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2824.12004
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.28/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.28/System.Drawing.Common.dll
----------------------------------------
ScottPlot
    Assembly Version: 5.0.22.0
    Win32 Version: 5.0.22.0
    CodeBase: file:///C:/Users/<USER>/AppData/Local/Temp/Rar$EXa80260.18640/scottplot-5.0-demo-winforms/ScottPlot.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2824.12004
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.28/Accessibility.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Numerics.Vectors.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.ComponentModel.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.28/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Memory.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2824.12004
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.28/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Linq.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.28/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
ScottPlot Cookbook
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/<USER>/AppData/Local/Temp/Rar$EXa80260.18640/scottplot-5.0-demo-winforms/ScottPlot%20Cookbook.dll
----------------------------------------
System.Resources.Writer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Resources.Writer.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.28/System.Configuration.ConfigurationManager.dll
----------------------------------------
SkiaSharp
    Assembly Version: 2.88.0.0
    Win32 Version: 2.88.7.0
    CodeBase: file:///C:/Users/<USER>/AppData/Local/Temp/Rar$EXa80260.18640/scottplot-5.0-demo-winforms/SkiaSharp.dll
----------------------------------------
System.Xml.XDocument
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Xml.XDocument.dll
----------------------------------------
System.Private.Xml.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Private.Xml.Linq.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Private.Xml.dll
----------------------------------------
ScottPlot.WinForms
    Assembly Version: 5.0.22.0
    Win32 Version: 5.0.22.0
    CodeBase: file:///C:/Users/<USER>/AppData/Local/Temp/Rar$EXa80260.18640/scottplot-5.0-demo-winforms/ScottPlot.WinForms.dll
----------------------------------------
SkiaSharp.Views.WindowsForms
    Assembly Version: 2.88.0.0
    Win32 Version: 2.88.7.0
    CodeBase: file:///C:/Users/<USER>/AppData/Local/Temp/Rar$EXa80260.18640/scottplot-5.0-demo-winforms/SkiaSharp.Views.WindowsForms.dll
----------------------------------------
SkiaSharp.Views.Desktop.Common
    Assembly Version: 2.88.0.0
    Win32 Version: 2.88.7.0
    CodeBase: file:///C:/Users/<USER>/AppData/Local/Temp/Rar$EXa80260.18640/scottplot-5.0-demo-winforms/SkiaSharp.Views.Desktop.Common.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Diagnostics.Process.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Collections.Concurrent.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Runtime.Loader.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Threading.ThreadPool.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2824.12007
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.28/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************
```

**Comment by TheFizz** [comment]
Happens to me too
