### ISSUE TITLE
ScottPlot get_legend method non-existent in ScottPlot.WPF 5.0.27-up

### ISSUE THREAD

**Issue by CaptainPicarl** [ScottPlot/ScottPlot#3875]
**Issue:** 
When exiting a method that initializes a scottplot - on exit it appears that get_Legend() is called and the method is not present.
I suspect this may be getting called when the plot is added to a WPF-visible control.

**Error Details:**
```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'ScottPlot.Legends.Legend ScottPlot.Plot.get_Legend()'.
  Source=PartSwapperXMLSE
  StackTrace:
   at PartSwapperXMLSE.WeaponcoreStats.generateWeaponRangesScttPltWPF() in C:\Users\{picarl}\source\repos\CaptainPicarl\PartSwapperXMLSE\PartSwapperXMLSE\WeaponcoreStats.cs:line 2363
   at PartSwapperGUI.WeaponcoreStatsWindow..ctor(ConfigOptions config) in C:\Users\{picarl}\source\repos\CaptainPicarl\PartSwapperXMLSE\PartSwapperGUI\WeaponcoreStatsWindow.xaml.cs:line 42
   at PartSwapperGUI.MainWindow.weaponcoreStatsButton_Click(Object sender, RoutedEventArgs e) in C:\Users\{picarl}\source\repos\CaptainPicarl\PartSwapperXMLSE\PartSwapperGUI\MainWindow.xaml.cs:line 244
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs:line 206
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/UIElement.cs:line 2340
   at System.Windows.Controls.Primitives.ButtonBase.OnClick() in /_/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/ButtonBase.cs:line 72
   at System.Windows.Controls.Button.OnClick() in /_/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Button.cs:line 273
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e) in /_/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/ButtonBase.cs:line 504
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/RoutedEventArgs.cs:line 335
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs:line 206
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/UIElement.cs:line 2286
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/RoutedEventArgs.cs:line 335
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs:line 206
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/UIElement.cs:line 2340
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Generated/UIElement.cs:line 457
   at System.Windows.Input.InputManager.ProcessStagingArea() in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputManager.cs:line 805
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputProviderSite.cs:line 105
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs:line 1438
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs:line 527
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs:line 1592
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in /_/src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/HwndWrapper.cs:line 330
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) in /_/src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/HwndSubclass.cs:line 433
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) in /_/src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Threading/ExceptionWrapper.cs:line 137
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) in /_/src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Threading/ExceptionWrapper.cs:line 46
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) in /_/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs:line 1350
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/HwndSubclass.cs:line 378
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) in /_/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs:line 2143
   at System.Windows.Application.RunDispatcher(Object ignore) in /_/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs:line 2406
   at System.Windows.Application.RunInternal(Window window) in /_/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs:line 1693
   at PartSwapperGUI.App.Main()
```
**ScottPlot Version:** (What NuGet package are you using?)
This issue is present in ScottPlot.WPF 5.0.27 onward.
ScottPlot.WPF 5.0.26 does not have this issue.

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples
_Will edit with code sample as soon as I can reproduce_

**Comment by MCF** [comment]
The legend is available through the Legend property on the Plot object.  There is a fair amount of customization around the legend object as well.  The cookbook has a lot of documentation about this:

https://scottplot.net/cookbook/5.0/Legend/

**Comment by swharden** [comment]
Hi @CaptainPicarl, thanks for reporting this! There hasn't been any movement on this issue in a while, so if you can provide a code sample we can run that reproduces the issue let us know and we can open this issue back up and take a closer look together 👍
