### ISSUE TITLE
AxisManager: Exception through when DateTimeXAxis fails to recall

### ISSUE THREAD

**Issue by githubkau** [ScottPlot/ScottPlot#3927]
```
ScottPlot.AxisPanels.DateTimeXAxis Min=45448.54982218345, Max=45448.54999643924, Span=0.00017425578698748723' was not present in the dictionary
```

SignalXY Plot with 4 signals and an additional right hand side y-axis and a DateTime x-Axis

5.0.34

```
The given key 'ScottPlot.AxisPanels.DateTimeXAxis Min=45448.54982218345, Max=45448.54999643924, Span=0.00017425578698748723' was not present in the dictionary.
   at ScottPlot.Control.MultiAxisLimitManager.Apply(Plot plot)
   at ScottPlot.Control.StandardActions.DragZoom(IPlotControl control, MouseDrag drag, LockedAxes locked)
   at ScottPlot.Control.Interaction.MouseDrag(Pixel from, Pixel to, MouseButton button, IEnumerable`1 keys, MultiAxisLimitManager start)
   at ScottPlot.Control.Interaction.OnMouseMove(Pixel newPosition)
   at ScottPlot.WPF.WpfPlotBase.SKElement_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Unfortunately it cannot reliably reproduce it, but it usually happens when panning the plot. Maybe using a try/catch in MultiAxisLimitManager.Apply would fix it, but that wouldn't solve the underlying problem.

**Comment by swharden** [comment]
Thanks for reporting this!

Note, we may be able to fix this issue by adding a check here to return early if the key is not in the array

https://github.com/ScottPlot/ScottPlot/blob/9c45ada1dd01677e1d3ce6f74f786b8deb07f4a2/src/ScottPlot5/ScottPlot5/Control/MultiAxisLimitManager.cs#L61-L69

A better fix may be to determine _why_ the key isn't there. I bet it's a floating point math issue.

**Comment by swharden** [comment]
Hi @githubkau, I know you said it isn't reliably reproducible, but I'm unable to reproduce it and I want to make sure that my code adequately describes your situation. Does this look right to you? Does it throw on your computer? If not, what has to change to make it through?

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/9927f80e-7bc6-41b1-a7c2-ab103fb558d9)

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        // SignalXY Plot with 4 signals
        List<ScottPlot.Plottables.SignalXY> signals = new();
        for (int i = 0; i < 4; i++)
        {
            DateTime[] xs = Generate.ConsecutiveDateTimes(10, DateTime.Now, TimeSpan.FromDays(1));
            double[] ys = Generate.RandomWalk(10);
            var sig = formsPlot1.Plot.Add.SignalXY(xs, ys);
            signals.Add(sig);
        }

        // an additional right hand side y-axis 
        var additionalAxisY = formsPlot1.Plot.Axes.AddRightAxis();

        // setup different signals to use different axes
        signals[2].Axes.YAxis = formsPlot1.Plot.Axes.Right;
        signals[3].Axes.YAxis = additionalAxisY;

        // and a DateTime x-Axis
        formsPlot1.Plot.Axes.DateTimeTicksBottom();
    }
}
```

Thanks for the additional information!

**Comment by githubkau** [comment]
The below code triggers the exception when you pan constantly while the chart is updated by the thread. It seems to be a thread safety issue. Any suggestions how to work around this programmatically would be appreciated. Maybe panning could be interrupted while drawing the chart.

<Window x:Class="scottcheck2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ScottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
        xmlns:local="clr-namespace:scottcheck2"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <ScottPlot:WpfPlot x:Name="Plot1"  ></ScottPlot:WpfPlot>
    </Grid>
</Window>

using System.Windows;

namespace scottcheck2 {
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window {


        public MainWindow() {
            InitializeComponent();
            //UpdateChart();
            var t = new Thread(UpdateChart);
            t.Start();
        }
        private void UpdateChart() {
            while (true) { Draw(); Thread.Sleep(2000); }
        }
        public void Draw() {
            List<double> xList = new List<double>();
            List<double> timeBuffer = new List<double>();
            List<double> cut = new List<double>();

            for (int i = 0; i < 2; i++) {
                DateTime dateTime = DateTime.Now;
                timeBuffer.Add(dateTime.ToOADate());

                xList.Add((float)(i));


            }

            Plot1.Plot.Clear();

            var xline = Plot1.Plot.Add.SignalXY(timeBuffer.ToArray(), xList.ToArray());

            Plot1.Refresh();
            Plot1.Plot.Axes.DateTimeTicksBottom();

        }

    }
}

**Comment by swharden** [comment]
Thanks for following-up @githubkau! It may be a little while before I can take a closer look, but it's possible this issue is due to multi-threading. See https://scottplot.net/faq/async/ for ideas that may help discover a fix before I'm able to take a closer look

**Comment by swharden** [comment]
Also I'm not exactly sure what your app is doing, but in case you haven't seem them check out these plot types:
* https://scottplot.net/demo/#plot-streaming-data
* https://scottplot.net/demo/#plot-growing-data

**Comment by githubkau** [comment]
Thanks for your advice. The way I updated the chart was wrong. I will follow the examples you pointed out.
