### ISSUE TITLE
Avalonia app freezes when when zooming into a Scatter very deeply

### ISSUE THREAD

**Issue by CodeDevAM** [ScottPlot/ScottPlot#3930]
**Issue:** Avalonia app freezes when when zooming into a Scatter very deeply

**ScottPlot Version:** 5.0.35 with Avalonia 11.1.0 beta2

I have a Scatter and when I zoom into the data very deeply the app freezes. The freeze is causes by exceptions that are thrown in the background very frequently.

```
Ausnahme ausgelöst: "System.InvalidOperationException" in ScottPlot.dll
[Visual]Exception in render loop: 'System.InvalidOperationException: limits returned by the autoscaler must always be in a good state
   at ScottPlot.AutoScalers.FractionalAutoScaler.GetAxisLimits(Plot plot, IXAxis xAxis, IYAxis yAxis)
   at ScottPlot.Rendering.RenderActions.AutoScaleUnsetAxes.AutoscaleUnsetAxesToData(Plot plot)
   at ScottPlot.Rendering.RenderActions.AutoScaleUnsetAxes.Render(RenderPack rp)
   at ScottPlot.Rendering.RenderManager.Render(SKCanvas canvas, PixelRect rect)
   at ScottPlot.Plot.Render(SKCanvas canvas, PixelRect rect)
   at ScottPlot.Avalonia.AvaPlot.CustomDrawOp.Render(ImmediateDrawingContext context)
   at Avalonia.Rendering.Composition.Drawing.ServerCompositionRenderData.Render(IDrawingContextImpl context)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, LtrbRect currentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Nullable`1 parentTransformedClip, IDirtyRectTracker dirtyRects)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.RenderRootToContextWithClip(IDrawingContextImpl context, ServerCompositionVisual root)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore(Boolean catchExceptions)
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderReentrancySafe(Boolean catchExceptions)
   at Avalonia.Rendering.Composition.Server.ServerCompositor.Render(Boolean catchExceptions)
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time)' (RenderLoop #65505271)
Das Programm "[2856] Desktop.exe" wurde mit Code 4294967295 (0xffffffff) beendet.

```

**Comment by danieljfarrell** [comment]
What does the plot look like before the app crashes? I'm also using ScottPlot with Avalonia, I have seen this happen once, and I managed to fix it somehow. I think I set a minimum zoom level. Another possibility, are you entering into a notification infinite loop? Sometimes with binding it is possible to generate change notifications forever.

**Comment by swharden** [comment]
Note that this is the region that is throwing...

https://github.com/ScottPlot/ScottPlot/blob/f0279f28c203218415f6f7b0a51606dab76bc36d/src/ScottPlot5/ScottPlot5/AutoScalers/FractionalAutoScaler.cs#L120-L121

A temporary fix could be to limit how far the user may zoom in using axis rules: https://scottplot.net/demo/5.0/#axis-rules

**Comment by CodeDevAM** [comment]
The freeze happens when I zoom into the plot very deeply so that only one or two points are visible.

Limiting the zoom is probably not going to work for me because I don't how to find a proper value for this limit.

Why is this exception even thrown? What is is used for? Why doesn't this function return a working default?

**Comment by CodeDevAM** [comment]
Catching the the exception with a modified `AutoScaler` and returning a default prevents the app to freeze.

```CSharp
internal class AutoScaler : IAutoScaler
{
    IAutoScaler _AutoScaler = new FractionalAutoScaler();

    public bool InvertedX
    {
        get => _AutoScaler.InvertedX;
        set => _AutoScaler.InvertedX = value;
    }
    public bool InvertedY
    {
        get => _AutoScaler.InvertedY;
        set => _AutoScaler.InvertedY = value;
    }

    public void AutoScaleAll(IEnumerable<IPlottable> plottables)
    {
        _AutoScaler.AutoScaleAll(plottables);
    }

    public AxisLimits GetAxisLimits(Plot plot, IXAxis xAxis, IYAxis yAxis)
    {
        AxisLimits result = new(-10.0, 10.0, -1.0, 1.0);
        try
        {
            result = _AutoScaler.GetAxisLimits(plot, xAxis, yAxis);
        }
        catch { }
        return result;
    }
}
```

Note: In my app I am setting the axes limits every time explicitly.

**Comment by swharden** [comment]
Hi @CodeDevAM, I'm actually unable to reproduce this locally using  two scatter plots. Can you share some code I may be able to use to reproduce this effect? Thanks!

**Comment by CodeDevAM** [comment]
I also struggle to create a minimal example for reproduction.

In my app i figured out that the y yxis triggers an AutoScale while the values of the x axis causes the exception to be thrown.

I think the code that is intended to deal with equal value does not work for big double values.
https://github.com/ScottPlot/ScottPlot/blob/f0279f28c203218415f6f7b0a51606dab76bc36d/src/ScottPlot5/ScottPlot5/AutoScalers/FractionalAutoScaler.cs#L106

![grafik](https://github.com/ScottPlot/ScottPlot/assets/125025268/acfd9cbf-9a6c-42bf-af01-5e18fad7c243)

Adding/subtracting a portion of the value like (`0.9999 * limits.Left and 1.0001 * limits.Right`) might be better than adding absolute values in such a case.

**Comment by swharden** [comment]
> I also struggle to create a minimal example for reproduction.



Got it! Thanks for following-up with your thorough description. This reproduces the error:

```cs
[Test]
public void Test_Autoscale_ExtremelyLarge()
{
    Plot plot = new();
    plot.Add.Marker(1e100, 1e100);
    plot.Should().RenderInMemoryWithoutThrowing();
}
```

Thanks again for reporting this! I'll fix it now 🚀
