### ISSUE TITLE
libSkiaSharp missing error - Azure function (windows)

### ISSUE THREAD

**Issue by HughGrovesArup** [ScottPlot/ScottPlot#4129]
**Question:** (Ask your question here)
Hi, I'm getting the `libSkiaSharp` missing error that has been reported a few times here.

I tried including `SkiaSharp.NativeAssets.Linux.NoDependencies` but to no help.

The difference seems to be that I'm trying to run my code from a Windows Azure function.

Any ideas what else I should try? I really seem to be struggling to get a `libSkiaSharp.dll` to appear in my output directories (even in the `runtimes` folder).

**ScottPlot Version:** (What NuGet package are you using?)
5.0.37

**Full error message**

```cs
Error: System.TypeInitializationException: The type initializer for 'ScottPlot.Fonts' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at SkiaSharp.SkiaApi.sk_typeface_ref_default()
   at SkiaSharp.SKTypeface..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKTypeface.get_Default()
   at ScottPlot.FontResolvers.SystemFontResolver.InstalledSansFont()
   at ScottPlot.Fonts..cctor()
   --- End of inner exception stack trace ---
   at ScottPlot.Fonts.get_Default()
   at ScottPlot.LabelStyle..ctor()
   at ScottPlot.Plottables.Benchmark..ctor()
   at ScottPlot.Plot..ctor()
   at Datacentres.Diagrams.HistogramWeather(List`1 weatherFile) in C:\Users\Hugh.Groves\Documents\Repos\datacentres\datacentres\Report.cs:line 198
   at Datacentres.Report.GenerateHTMLReport(DataCentre dc) in C:\Users\Hugh.Groves\Documents\Repos\datacentres\datacentres\Report.cs:line 31
   at Datacentres.Mechanical.Calculations.PowerUsage(String moduleTypes, String moduleDefinitions, List`1 precedents, List`1 dependents, List`1 weatherStepLabels, List`1 weatherStepHours, List`1 weatherStepDryBulbs) in C:\Users\Hugh.Groves\Documents\Repos\datacentres\datacentres\Mechanical.cs:line 50
```

**Comment by HughGrovesArup** [comment]
Should also add - runs fine locally on my windows development machine (even though no libSkiaSharp.dll seems to get generated). I'm using `net6.0`.

**Comment by epegeot** [comment]
Hello, it would be interesting to know what is the platform behind this Azure service, you nay need a different `NativeAssets.*.NoDependencies` depending on what is the running environment behind. I had this problem when building for x86 where I needed to add the Win32 assets from SkiaSharp (`SkiaSharp.NativeAssets.Win32.NoDependencies`).

**Comment by epegeot** [comment]
Another problem that may exist is dependent on how you are publishing your project to Azure, have you tried things like in this thread?

https://stackoverflow.com/questions/76117418/libskiasharp-dll-can-not-be-loaded-in-azure-function-environment

**Comment by HughGrovesArup** [comment]
I've had a look and it seems like the azure function is setup to use 64-bit (same as my local dev machine).

![image](https://github.com/user-attachments/assets/bfd6fc79-2ee2-40d6-9782-9ba548dc2c66)

**Comment by HughGrovesArup** [comment]
For others in the same spot I managed to get it to work for me by setting the runtime identifier in the .csproj file to exactly what I needed i.e. `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` - I then got a `libSkiaSharp.dll` amongst my other .dlls.
