### ISSUE TITLE
Suggestion for Handling Plot Injection with IPlotControl.Reset(Plot plot)

### ISSUE THREAD

**Issue by Koji-Morimoto** [ScottPlot/ScottPlot#4365]
**Suggestion:**
I am trying to inject a Plot into different UI framework implementations of IPlotControl by creating the Plot first, then using the Reset method of IPlotControl to inject it, rather than creating the IPlotControl and then adding plots to it with IPlotControl.Plot.Add.

In this Plot, I intended not only to display the plot but also to use SingleClickResponse to enable interactions through click events. However, I encountered the following exception:

```cs
public static void BindTo(this Plot plot, IPlotControl plotView)
{
    plotView.Reset(plot);// This plot was created before this method is called, in a shared project across multiple UI frameworks.

    plotView.Interaction.IsEnabled = false;
    plotView.UserInputProcessor.IsEnabled = true;

    SingleClickResponse clickResponse = new SingleClickResponse(
            ScottPlot.Interactivity.StandardMouseButtons.Left,
            (Plot, pt) =>
            {
                var coordinate = plot.GetCoordinates(pt);
                /*This is to confirm that the click event is being handled. */
                var arrow = plot.Add.Arrow(coordinate.X, coordinate.Y, coordinate.X + 1, coordinate.Y + 1);
                arrow.ArrowStyle.ArrowWidth = 10;
                arrow.ArrowStyle.ArrowheadWidth = 10;
                plotView.Refresh();
            }
        );
}
```

```cs
       System.NullReferenceException: Object reference not set to an instance of an object.
       at ScottPlot.Plot.GetPanel(Pixel pixel, Boolean axesOnly)
       at ScottPlot.Plot.GetAxis(Pixel pixel)
       at ScottPlot.Interactivity.MouseAxisManipulation.DragPan(Plot plot, Pixel mouseDown, Pixel mouseNow)
       at ScottPlot.Interactivity.UserActionResponses.MouseDragPan.ApplyToPlot(Plot plot, Pixel px1, Pixel px2, KeyboardState keys)
       at ScottPlot.Interactivity.UserActionResponses.MouseDragPan.Execute(Plot plot, IUserAction userInput, KeyboardState keys)
       at ScottPlot.Interactivity.UserInputProcessor.ExecuteUserInputResponses(IUserAction userAction)
       at ScottPlot.Interactivity.UserInputProcessor.Process(IUserAction userAction)
       at ScottPlot.WinForms.FormsPlotExtensions.ProcessMouseUp(UserInputProcessor processor, MouseEventArgs e)
       at ScottPlot.WinForms.FormsPlotBase.SKElement_MouseUp(Object sender, MouseEventArgs e)
       at System.Windows.Forms.Control.OnMouseUp(MouseEventArgs e)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**After adding the following code, the exception no longer occurred.**

```cs
  plotView.UserInputProcessor.Plot = plot;
```

**Would it be possible to add this code to IPlotControl.Reset(Plot plot)?**

```cs
//This is from ScottPlot.WinForms.FormsPlotBase
  public void Reset(Plot plot)
  {
      Plot plot2 = Plot;
      Plot = plot;
      plot2?.Dispose();
      Plot.PlotControl = this;
      this.UserInputProcessor.Plot = this.Plot;//Suggestion code.
  }
```

**Comment by swharden** [comment]
Hi @Koji-Morimoto, I think this was fixed in #4404 and should be working in the current version on NuGet 👍
