### ISSUE TITLE
Controls: `Reset()` does not update the `UserInputProcessor`

### ISSUE THREAD

**Issue by Or8e4m4n** [ScottPlot/ScottPlot#4404]
It seems that is no longer possible to pan or zoom charts with the version 5.0.41, but works fine with the previous version (at least with Scatter and Bar charts.

```
   at ScottPlot.Plot.GetPanel(Pixel pixel, Boolean axesOnly)
   at ScottPlot.Plot.GetAxis(Pixel pixel)
   at ScottPlot.Interactivity.MouseAxisManipulation.MouseWheelZoom(Plot plot, Double fracX, Double fracY, Pixel pixel, Boolean ChangeOpposingAxesTogether)
   at ScottPlot.Interactivity.UserActionResponses.MouseWheelZoom.Execute(Plot plot, IUserAction userInput, KeyboardState keys)
   at ScottPlot.Interactivity.UserInputProcessor.ExecuteUserInputResponses(IUserAction userAction)
   at ScottPlot.Interactivity.UserInputProcessor.Process(IUserAction userAction)
   at ScottPlot.WPF.WpfPlotExtensions.ProcessMouseWheel(UserInputProcessor processor, FrameworkElement fe, MouseWheelEventArgs e)
   at ScottPlot.WPF.WpfPlotBase.SKElement_MouseWheel(Object sender, MouseWheelEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Software.Desktop.App.Main()
```

Can you please investigate?

**Comment by swharden** [comment]
Note that I just followed the steps in the quickstart using the latest version of ScottPlot and it works as expected, so any information about how to recreate this issue would be really helpful.

```cs
namespace WinFormsApp2
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            double[] dataX = { 1, 2, 3, 4, 5 };
            double[] dataY = { 1, 4, 9, 16, 25 };

            formsPlot1.Plot.Add.Scatter(dataX, dataY);
            formsPlot1.Refresh();
        }
    }
}
```

![image](https://github.com/user-attachments/assets/32b061a5-828f-4fa5-b084-e62f916f7aab)

**Comment by Or8e4m4n** [comment]
Thanks for your feedbacks.

Sorry, it was some obvious in my mind that I didn't mention that the issue occurs with WPF.

I've just realized that before drawing on the plot I call `Reset()` which seems to cause the issue. If you add `formsPlot1.Reset()` at the beginning. The plot will be generated, but then causes the issue when panning or zooming.

I'll have a closer look what `Reset()` is actually used for.

**Comment by swharden** [comment]
Thanks for clarifying @Or8e4m4n!

I think the issue is here. At startup the user input processor gets set-up:

https://github.com/ScottPlot/ScottPlot/blob/9c149dd845d1a20a002098a67ac6aac413bea85a/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WPF/WpfPlotBase.cs#L32-L40

But after `Reset()` is called it is not set-up with the new plot:

https://github.com/ScottPlot/ScottPlot/blob/9c149dd845d1a20a002098a67ac6aac413bea85a/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WPF/WpfPlotBase.cs#L47-L53

I'll fix this and publish a new package this evening!

**Comment by swharden** [comment]
Hi @Or8e4m4n, I believe this has been fixed by @4406 which was just merged.

I released https://github.com/ScottPlot/ScottPlot/releases/tag/5.0.42 and it should be on NuGet in about 30 minutes.

If you give it a try I'd love to confirm it works as expected in your hands!

Thanks again for reporting this 👍

**Comment by Or8e4m4n** [comment]
Thanks Scott for your update. It doesn't cause the issue anymore, but like I said I don't really know what `Reset()` is used for and I think I don't actually require it. I used it to "reset" the panning / zooming when navigating from one chart to another (via a ribbon), but I actually redraw them every time (which can probably be improved as it takes a few seconds to render them - I overlay several plots for each chart).
