### ISSUE TITLE
On dotnet 9 Scottplot Blazor demo code fails due to SkiaSharp issue

### ISSUE THREAD

**Issue by xela-trawets** [ScottPlot/ScottPlot#4584]
**Issue:** with a new dotnet 9 project following the Scottplot demo for blazor fails at run time because libskiasharp.dll fails to load. This same project works fine in dotnet 8.

**ScottPlot Version:** (What NuGet package are you using?)
5.0.47

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples
Demo code for blazor from 
[https://scottplot.net/quickstart/blazor/](url)

This issue seems to be under active investigation
[https://github.com/mono/SkiaSharp/issues/3068](url) and a fix is in preview.

But the version of skiasharp currently used in Scottplot will need updating for dotnet 9.

**Comment by bclehmann** [comment]
For context, ScottPlot.Blazor currently depends on version 2.88.9 or higher. It looks to be fixed in `3.118.0-nightly.27`, I'm not sure if it will be backported to 2.x or not. I suspect it will be since 3.x isn't out of preview yet.

If it is backported then our users should be able to update SkiaSharp.Views.Blazor themselves. But we should probably at least document it somewhere. We could also require the new version for them, though I don't know if I want to impose something like that on our users if they're not on NET 9.

I think we could impose it for NET 9 users and not others, similar to how we add packages for NET Framework users but not others: https://github.com/ScottPlot/ScottPlot/blob/2389ab65784525b67d4e23cb3cf8fabe3df5c0a5/src/ScottPlot5/ScottPlot5/ScottPlot.csproj#L58-L60

**Comment by xela-trawets** [comment]
Right.  There are other projects affected, so there may well be an upstream fix.
To make this google-able here is the exception (which is misleadingly about fonts)

from the browser console 
blazor.webassembly.js:1  System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception.

from the "output" in vs 2022
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception.
 ---> System.DllNotFoundException: libSkiaSharp
   at SkiaSharp.SKTypeface..cctor()
   --- End of inner exception stack trace ---
   at ScottPlot.FontResolvers.SystemFontResolver.InstalledSansFont()
   at ScottPlot.Fonts..cctor()
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'ScottPlot.Fonts' threw an exception.
System.TypeInitializationException: The type initializer for 'ScottPlot.Fonts' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception.
 ---> System.DllNotFoundException: libSkiaSharp
   at SkiaSharp.SKTypeface..cctor()
   --- End of inner exception stack trace ---
   at ScottPlot.FontResolvers.SystemFontResolver.InstalledSansFont()
   at ScottPlot.Fonts..cctor()
   --- End of inner exception stack trace ---

**Comment by idotta** [comment]
Did anyone find a workaround for this? Or should we just use .NET8 for now?

**Comment by xela-trawets** [comment]
I think its connected with the deprecation of the unmanaged JSRuntime interop in dotnet 9. - so while there might not be a simple workaround, a real fix might not be that painful 

For the time being .NET8 is the way to go. - which is a bit frustrating, cos the new stuff is shiny.

I am trying not to look at the fork button...

**Comment by swharden** [comment]
It seems that SkiaSharp 3 is out of preview...
https://www.nuget.org/packages/SkiaSharp/#versions-body-tab

Can someone confirm if updating this dependency version in the main branch of the ScottPlot repo solves this issue?

I intend to take the next several days to close some of the smaller open issues, but if someone gives this 2->3 version bump and reports that it is really easy then I will be highly motivated to update this dependency across all packages and publish a new package on NuGet in good time.

Thanks!

**Comment by xela-trawets** [comment]
Trying that... I think we need SkiaSharp 3.118 - which is not out of preview yet.
(SkiaSharp 3.116 is released - but still has blazor interop issues reported on dotnet 9).
I have forked ScottPlot to try the different combinations, but am floundering a bit with the VS tools.
Getting undefined symbol errors - so there may be transitive dependency mismatches.

**Comment by xela-trawets** [comment]
To be specific in dotnet 8 with Skiasharp 3.118 the canvas doesnt show up in debug mode, but does in release mode. 
Also the mouse interaction seems to be disconnected, even in release mode. 
My 2 cents is to see what goes on over in skiasharp, at least until 3.118 is released
We may not be too far off - here is a picture 
![image](https://github.com/user-attachments/assets/6d496030-a6dc-4c03-a3c2-ba18460ecc79)

**Comment by xela-trawets** [comment]
> I'm also experimenting with Scottplot + NET9 Blazor Wasm. On my end, it works fine with SkiaSharp 3.116.1, just there is no interaction. There was indeed a bug in SkiaSharp before that broke things for .NET9, but as far as know this is fixed in 3.116.1.
> 
> @xela-trawets you mentioned interaction is "disconnected"; is there a way to connect is again? Or does this require updates to code in either SkiaSharp and/or Scottplot?

This sounds most promising !

I will try the released SkiaSharp version 3.116, which I had avoided due to mentions in some similar issues.
I am looking at the Skia code. I will know more after the weekend,

**Comment by LeaFrock** [comment]
> I'm also experimenting with Scottplot + NET9 Blazor Wasm. On my end, it works fine with SkiaSharp 3.116.1, just there is no interaction.

@mennowo `UserInputProcessor.Enable()` doesn't work too after upgrading my Blazor Wasm to .NET 9. Is it still an issue of SkiaSharp?

**Comment by mennowo** [comment]
Just for reference: to load a non-default font in a WASM context, you need to embed it in the application, since WASM cannot by itself retrieve this from browser resources or similar. I'm not sure how this could work in the case of ScottPlot. [Here](https://github.com/oxyplot/oxyplot/blob/989df42a75cfc1ef5751afe3f9eb859bc9e62ded/Source/OxyPlot.SkiaSharp/SkiaRenderContext.cs#L871) is visible how this works in OxyPlot. I found it rather hard to find explicit information about this, so I am posting this just in case.

**Comment by xela-trawets** [comment]
Sorry for the Delay - Irealize I promised to look at the Skia issue.. Am away dealing with a family thing.

**Comment by Gerardo-Sista** [comment]
Same here, not working with blazor wasm .net9 due to skiasharp problems.  :(

**Comment by xela-trawets** [comment]
Skiasharp 3.118 preview 2.3 is working - with mouse and everything in a simple test under dotnet 9... So I will take it for a spin in scotplot. 
(May still have some font issues [https://github.com/mono/SkiaSharp/issues/1902](url))

**Comment by xela-trawets** [comment]
Things are working for me once I avoid "server prerendering". There is a mixup on the mouse button translation I think. I will try and pull together a PR to fix the mouse issues. 
The prerendering is terrible because it causes things like SKTypeface.Default to be called. 
This is why dotnet 9 (Blazor) broke the demo. It is not enough to use rendermode interactivewebassembly, we need to disable prerender.

**Comment by xela-trawets** [comment]
The demo works (with working (default) mouse drag and zoom)
- Using the released version of skiasharp.views.blazor 3.116,  
- Dotnet 9
- Small changes to the ScottPlot.Blazor component: 
`
@code {
    private SKCanvasView? SKView { get; set; } = OperatingSystem.IsBrowser() ? new() : null;

    public void OnPaintSurface(SKPaintSurfaceEventArgs e)
    {
        Multiplot.Render(e.Surface);
    }

    public override void Refresh()
    {
        SKView?.Invalidate();
    }
}
`

**Comment by xela-trawets** [comment]
I will put a PR together.

A couple of issues in making a pull request 
firstly, it seems best to update skia sharp across the solution, but that touches everything.
secondly, need to test this across versions, maybe just 7, 8, 9 

(like the old joke "why was 6 frightened ?? ) 

Mixing rendermodes can still be a bit tricky, 
I was also seeing some "old version issues" perhaps from the tool chain.

**Comment by xela-trawets** [comment]
The PR test fails due to "multiple SkiaSharp versions found"
This is intentional, I only touched the Blazor control.
I did try updating all the projects to SkiaSharp 3.116.1.
Didnt test that, it seems a big step.

Happy to do that if we want that

Alex

**Comment by xela-trawets** [comment]
Made a PR,
https://github.com/ScottPlot/ScottPlot/pull/4816
SkiaSharp 3.116.1 , and a fix around dotnet 9 prerender.
Closed it while thinking about a solution for server-side blazor render mode

**Comment by xela-trawets** [comment]
just found this thing
[https://github.com/jsakamoto/BlazorWasmPreRendering.Build](url)
Looks better than the alternative..

![Image](https://github.com/user-attachments/assets/ed1e7493-a7aa-446c-a7f8-81899367fdd4)

**Comment by caterryan** [comment]
@LeaFrock I already have wasm tools net9 installed. Maybe net8 is needed instead. I can try this later.

**Comment by LeaFrock** [comment]
Reinstall the wasm-tools. Also make sure no dependency packages have conflicts on the SkiaSharp version.

That's all the workloads in my local environment. ScottPlot works well in my Blazor WASM .NET 9 project.

```
dotnet workload list

aspire               8.2.2/8.0.100      SDK 9.0.300, VS 17.14.36221.1
wasm-tools           9.0.6/9.0.100      SDK 9.0.300                  
wasm-tools-net6      9.0.6/9.0.100      SDK 9.0.300, VS 17.14.36221.1
```

**Comment by jordiascension** [comment]
> Ok I finally got the ScottPlot.Blazor demo working with dotnet 9.0 To [get past this issue](https://github.com/ScottPlot/ScottPlot/issues/4584#issuecomment-3032523415) I had to use `dotnet clean` before building the project.
> 
> For anyone looking to get up and running, here are the exact steps I took to get everything to get this working.
> 
> ## 1) Install dotnet 9.0
> ## 2) Install wasm tools
> `dotnet workload install wasm-tools`
> 
> ## 3) Create a new Blazor WASM 9.0 project
> `dotnet new blazorwasm -f net9.0`
> 
> ## 4) Follow the instructions for the [ScottPlot demo](https://scottplot.net/quickstart/blazor/)
> Add the ScottPlot.Blazor Nuget Package `dotnet add package ScottPlot.Blazor`
> 
> Add a ScottPlot to a page. I replaced the contents of `Home.razor` with this
> 
> ```
> @page "/"
> @using ScottPlot
> @using ScottPlot.Blazor
> 
> <h1>ScottPlot 5 in Blazor</h1>
> 
> <BlazorPlot @ref=BlazorPlot Style="width: 400px; height: 300px;" />
> 
> @code {
> 
>     BlazorPlot BlazorPlot { get; set; } = new();
> 
>     protected override void OnAfterRender(bool firstRender)
>     {
>         BlazorPlot.Plot.Add.Signal(Generate.Sin());
>         BlazorPlot.Plot.Add.Signal(Generate.Cos());
>     }
> }
> ```
> 
> ## 5) Run the project
> `dotnet run`
> 
> Open the host url in a browser e.g. `http://localhost:5279` Note that your port will probably be different
> 
> The page should fail to load with this error
> 
> ```
> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: The type initializer for 'ScottPlot.Fonts' threw an exception.
> System.TypeInitializationException: The type initializer for 'ScottPlot.Fonts' threw an exception.
>  ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception.
>  ---> System.DllNotFoundException: libSkiaSharp
> ```
> 
> ## 6) Add additional dependencies per [@LeaFrock](https://github.com/LeaFrock)
> `dotnet add package SkiaSharp.HarfBuzz` `dotnet add package SkiaSharp.Views.Blazor` `dotnet add package HarfBuzzSharp.NativeAssets.Linux` `dotnet add package SkiaSharp.NativeAssets.Linux.NoDependencies`
> 
> Your .csproj should look like this
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
> 
>   <PropertyGroup>
>     <TargetFramework>net9.0</TargetFramework>
>     <Nullable>enable</Nullable>
>     <ImplicitUsings>enable</ImplicitUsings>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="8.3.1.1" />
>     <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.7" />
>     <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.7" PrivateAssets="all" />
>     <PackageReference Include="ScottPlot.Blazor" Version="5.0.55" />
>     <PackageReference Include="SkiaSharp.HarfBuzz" Version="3.119.0" />
>     <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.0" />
>     <PackageReference Include="SkiaSharp.Views.Blazor" Version="3.119.0" />
>   </ItemGroup>
> 
> </Project>
> ```
> 
> ## 7) Run the project
> `dotnet run`
> 
> Open the host url in a browser
> 
> The page should fail to load with this error
> 
> ```
> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: The type initializer for 'ScottPlot.Fonts' threw an exception.
> System.TypeInitializationException: The type initializer for 'ScottPlot.Fonts' threw an exception.
>  ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception.
>  ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
>  ---> System.InvalidOperationException: The version of the native libSkiaSharp library (119.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).
> ```
> 
> ## 8) Clean the project
> `dotnet clean`
> 
> ## 9) Run the project
> `dotnet run`
> 
> Open the host url in a browser
> 
> The plot should render correctly.
> 
> I tested this on both Windows and Linux.

It works perfectly!! I have created a demo project:  https://github.com/jordiascension/ScottPlotBlazorNetCore9

**Comment by jordiascension** [comment]
I have created a demo project from [caterryan](https://github.com/caterryan) solution: https://github.com/jordiascension/ScottPlotBlazorNetCore9
