### ISSUE TITLE
Error saying haven't got 'System.Drawing.Common, Versions=4.0.0.1' - WinForm VB.net

### ISSUE THREAD

**Issue by vrdriver** [ScottPlot/ScottPlot#924]
Hi Scott, this is a bit of a curly question, as I don't know why things are happening this way.

Some slight background on this, as it has happened before with my current app instance...

I am working on a program using VS 16.9.2, and my program is a VB.NET Winform app, rather than using C#.
My program has been working fine, but then when I try and add a SP chart to the program, I get a nice little ambiguous error. 
I can add SP and SP.WinForms through NuGet and it adds  tem to the application fine, but, when I try to add a SP chart to a form, I get a popup message, telling me that I haven't got 'System.Drawing.Common, Versions=4.0.0.1' etc installed...  

![Screen Shot 2021-03-29 at 13 40 40](https://user-images.githubusercontent.com/5615487/112780333-5c1e9600-9094-11eb-8645-1c779b5b34f1.png)

I know that I'm fulfilling the requirements of SP, as I have version 4.0.0.2 installed, and the latest version of SP as well. (4.0.48)

![Screen Shot 2021-03-29 at 13 42 11](https://user-images.githubusercontent.com/5615487/112780444-92f4ac00-9094-11eb-89e8-8bc0edf81e69.png)

![Screen Shot 2021-03-29 at 13 52 34](https://user-images.githubusercontent.com/5615487/112781168-05b25700-9096-11eb-9d1d-e7b156e89449.png)

So, I did some testing and recreated the project like before using .NET Framework 4.7.2, (fortunately it's only a single form application so it's not too hard), and it all worked and I was able to add SP items. However, since then I have been using it, I am once again having the same error appear

The thing is the error is now in a different place when I try to open up the Design view of my form.

I saw that someone else had a similar problem, but not exactly: https://github.com/ScottPlot/ScottPlot/discussions/655

Do you have any suggestions, or know why it would work, and then after a while decide to not want to load the Design view? 

Here's a screen shot of the error, along with the text as well.

![Screen Shot 2021-03-29 at 13 33 40](https://user-images.githubusercontent.com/5615487/112779875-61c7ac00-9093-11eb-9fc8-8f8d3d9d403a.png)

```cs
    To prevent possible data loss before loading the designer, the following errors must be resolved:    
    
   Could not load file or assembly 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.     
    
Instances of this error (3)  
 
1.   Hide Call Stack 
 
at ScottPlot.Renderable.GridLines..ctor()
at ScottPlot.Settings..ctor()
at ScottPlot.Plot..ctor(Int32 width, Int32 height)
at ScottPlot.FormsPlot.Reset(Plot plt)
at ScottPlot.FormsPlot..ctor()  
 
2.   Hide Call Stack 
 
at ScottPlot.Renderable.GridLines..ctor()
at ScottPlot.Settings..ctor()
at ScottPlot.Plot..ctor(Int32 width, Int32 height)
at ScottPlot.FormsPlot.Reset(Plot plt)
at ScottPlot.FormsPlot..ctor()  
 
3.   Hide Call Stack 
 
at ScottPlot.Renderable.GridLines..ctor()
at ScottPlot.Settings..ctor()
at ScottPlot.Plot..ctor(Int32 width, Int32 height)
at ScottPlot.FormsPlot.Reset(Plot plt)
at ScottPlot.FormsPlot..ctor()  
 
Help with this error  
 
Could not find an associated help topic for this error. Check Windows Forms Design-Time error list   
 
   The variable 'FormsPlot3' is either undeclared or was never assigned.     Go to code  
     
Instances of this error (1)  
 
1.   WindowsApp1 Form1.Designer.vb Line:888 Column:1   Show Call Stack  
 
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.Error(IDesignerSerializationManager manager, String exceptionText, String helpLink)
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(IDesignerSerializationManager manager, String name, CodeExpression expression)
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(IDesignerSerializationManager manager, String name, CodeExpression expression)
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeStatement(IDesignerSerializationManager manager, CodeStatement statement)  
 
  
   The variable 'FormsPlot2' is either undeclared or was never assigned.     Go to code  
     
 
Instances of this error (1)  
 
1.   WindowsApp1 Form1.Designer.vb Line:890 Column:1   Show Call Stack  
 
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.Error(IDesignerSerializationManager manager, String exceptionText, String helpLink)
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(IDesignerSerializationManager manager, String name, CodeExpression expression)
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(IDesignerSerializationManager manager, String name, CodeExpression expression)
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeStatement(IDesignerSerializationManager manager, CodeStatement statement)  
 
  
   The variable 'FormsPlot1' is either undeclared or was never assigned.     Go to code   
  
 
Instances of this error (1)  
 
1.   WindowsApp1 Form1.Designer.vb Line:891 Column:1   Show Call Stack  
 
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.Error(IDesignerSerializationManager manager, String exceptionText, String helpLink)
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(IDesignerSerializationManager manager, String name, CodeExpression expression)
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(IDesignerSerializationManager manager, String name, CodeExpression expression)
at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeStatement(IDesignerSerializationManager manager, CodeStatement statement)  

```

As you can see, it's a bit on the weird side, yet my program still compiles and runs fine...

**Comment by swharden** [comment]
Hi @vrdriver!

I'm a bit short on time so forgive how brief my answer is, but I recall this may be an issue related to compiling a 64-bit program but the visual studio designer is only a 32-bit program.

You could try to clear all your packages/binaries, change your project settings to target a 32-bit build, rebuild all, restart visual studio, cross your fingers and hold your tongue at just the right angle and it might work again... does that solve your problem?

**Comment by vrdriver** [comment]
Hmm... I'll look in to that aspect as see how I go. I may have to cross my toes as well. Cheers.

**Comment by vrdriver** [comment]
I've played around with this now, and I think I may have solved it by doing the following:

-Use 'Any CPU' (which I was still doing).
-Use the current BETA build of SP 4.1.10-beta.

At least when I close and reopen the program it will display the SP elements on the form now. Weird, but you pointed me in the right direction again. 
Thanks mate.
-Steve
